### ISSUE TITLE
Invalid line breaks in the top1000 TSV files of the reranking datasets

### ISSUE THREAD

**Issue by spacemanidol** [microsoft/MSMARCO-Passage-Ranking#1]
Describe the bug

A lot of invalid line breaks are contained in the top1000 TSV files of the reranking datasets.
For example, line 234472 in the top1000.dev.tsv does not start with the IDs.

To Reproduce

% sed -n 234471,234472p top1000.dev.tsv
1082445 3492590 what does unlock my device mean iOS: Understanding the SIM PIN.
 You can lock your SIM card so that it can't be used without a Personal Identification Number (PIN).

**Comment by spacemanidol** [comment]
copied from https://github.com/dfcf93/MSMARCO/issues/31

**Comment by amirj** [comment]
Thanks for sharing this valuable dataset.
As this dataset has been leveraged by [TREC-2019 Deep Learning Track](https://github.com/microsoft/TREC-2019-Deep-Learning/issues/6), nobody can progress the reranking task without this top-1000 initial ranking file. It would be great if you can solve this issue as soon as possible.

**Comment by spacemanidol** [comment]
This issue should be solved later on today. Ill update this thread when this is fixed

**Comment by spacemanidol** [comment]
This is now fixed
