### ISSUE TITLE
On full-documents and passage alignement

### ISSUE THREAD

**Issue by Ricocotam** [microsoft/MSMARCO-Passage-Ranking#12]
Hi,
Is there an alignement available (or a script) for passages and full documents ?
Since passages are extracted from documents we should be able to have this information. Since the maintainer is present on a lot of MS-MARCO project, I was wondering if a release date for Document Rankin's data was available ?

**Comment by spacemanidol** [comment]
@Ricocotam  actually the passages were not extracted from these documents. The document corpus was crawled after the QnA dataset(which is the basis of the ranking task) was released. Thus there isn't a direct mapping. @bmitra-msft worked on a passage2url join I remember. Anything we can share broadly?

I am currently working on the evaluation method for the document ranking which I should be able to it out in March-ish. In the meantime, TREC has released the labels associated with the document ranking task ran in the 2019 Deep Learning Track.

**Comment by Ricocotam** [comment]
Oh ok, that's not what I understood from de paper. Thanks for the help

**Comment by bhaskar-mitra** [comment]
Unfortunately, we don't have any immediate plans to release any passage-to-document mapping.
