### ISSUE TITLE
Extracting qidpidtriples.train.full.tar.gz

### ISSUE THREAD

**Issue by davidmrau** [microsoft/MSMARCO-Passage-Ranking#14]
I am having troubles extracting `qidpidtriples.train.full.tar.gz`. The commands I ran:

1. `gunzip qidpidtriples.train.full.tar.gz` yielding the file `qidpidtriples.train.full.tar`
2. then running `tar -xf qidpidtriples.train.full.tar` I get the following error:

tar: This does not look like a tar archive
tar: Skipping to next header
tar: Archive contains '736889\t87209' where numeric off_t value expected
...

If I run `tar -xzvf qidpidtriples.train.full.tar.gz` directly I get the same error.

**Comment by davidmrau** [comment]
I also tried `gzip -d qidpidtriples.train.full.tar.gz` without success.

**Comment by davidmrau** [comment]
Found the solution to it. The file `qidpidtriples.train.full.tar` is not a tar file. 

`mv qidpidtriples.train.full.tar qidpidtriples.train.full.tsv` solves the  problem.

**Comment by spacemanidol** [comment]
Hey. Thanks for catching this. I've gone ahead and fixed this.
