### ISSUE TITLE
can't download triples.train.full.tsv.gz

### ISSUE THREAD

**Issue by insublee** [microsoft/MSMARCO-Passage-Ranking#15]
Hello, the file triples.train.full.tsv.gz is too big and I keep getting an error when downloading with wget. Is there an easy way to download it?
thank you.

**Comment by insublee** [comment]
and also, why "word-vocab-small.tsv" isn't encluded? i found it another repo.
https://github.com/spacemanidol/MSMARCO/tree/master/Ranking/Baselines/data

**Comment by insublee** [comment]
+
have to download "glove.6B.300d.txt" which is here.
https://github.com/stanfordnlp/GloVe

**Comment by spacemanidol** [comment]
try downloading the train triples small. The large requires a big and stable internet connection since its > 250 gb. Most models are just using the sample and its more than enough. The small is 1/10 sampled at random.

I've also gone an added the file you mentioned.
