### ISSUE TITLE
Can't download qidpidtriples.train.full.tar.gz

### ISSUE THREAD

**Issue by rodinasophie** [microsoft/MSMARCO-Passage-Ranking#16]
<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:5a650a97-c01e-00a0-6f93-ecde7b000000 Time:2020-02-26T10:54:09.0262111Z
</Message>
</Error>

**Comment by spacemanidol** [comment]
just tried the link on the website for me and worked well https://msmarco.blob.core.windows.net/msmarcoranking/qidpidtriples.train.full.tsv.gz

**Comment by rodinasophie** [comment]
>just tried the link on the website for me and worked well https://msmarco.blob.core.windows.net/msmarcoranking/qidpidtriples.train.full.tsv.gz

@spacemanidol, Thanks for the link, it's not working from the github-page - 
https://msmarco.blob.core.windows.net/msmarcoranking/qidpidtriples.train.full.tar.gz

tsv<->tar?
