### ISSUE TITLE
which column is the relevance label in the qrels file?

### ISSUE THREAD

**Issue by Huhao123** [microsoft/MSMARCO-Passage-Ranking#4]
You said "Please ignore columns 1 and 3. " when you introduced the qrels file. So , i wonder which  column is the relevance label?

**Comment by spacemanidol** [comment]
First off thought it was worth clarifying that I was indexing at 0 so there are 4 columns 0,1,2,3.  Column 0 is queryID, column 2 is passageID. Please ignore columns 1 and 3 they are part of the TREC QRELS style

**Comment by Huhao123** [comment]
so, you mean that the column 3 is the relevance label

**Comment by Huhao123** [comment]
so, all the queries and corresponding passages in the qrels file are relevant, if I understand correctly.
