### ISSUE TITLE
top-1000 train set contains ~5 retrieved passages on average

### ISSUE THREAD

**Issue by amirj** [microsoft/MSMARCO-Passage-Ranking#5]
Lets count the number of retrieved passages in [top1000.train.tar.gz](https://msmarco.blob.core.windows.net/msmarcoranking/top1000.train.tar.gz):

```
train_qids = []
with(open(PATH_PREFIX + 'queries.train.tsv')) as qcollection:
    for l in qcollection:
        qid, qtxt = l.strip().split('\t')
        train_qids.append(int(qid))

print('Number of train queries: %s' % (format(len(qids), ',')))

qid_serp = dict()
# top-1k train set
with tarfile.open(PATH_PREFIX + 'top1000.train.tar.gz', "r:gz") as top1k:
    for member in top1k.getmembers():
        f = top1k.extractfile(member)
        if f is not None:
            try:
                for l in f:
                    qid, did = l.decode('utf-8').strip().split('\t')[:2]
                    qid, did = map(int, [qid, did])
                    qid_serp.setdefault(qid, 0)
                    qid_serp[qid] += 1
            except:
                print('mis-format train doc: ', l)

print('Total queries presented in top-1000: %d' %(len(qid_serp.keys())))
print('Min number of retrieved passages: %d' %(min(qid_serp.values())))
print('Max number of retrieved passages: %d' %(max(qid_serp.values())))
```
This is the output:
```
Number of train queries: 808,731

mis-format train doc:  b' Your computer may display a reverse image if certain keys are pressed at the same time. Depending on your configuration, it may be black and white or inverted color, as shown below.\n'

Total queries presented in top-1000: 481780
Min number of retrieved passages: 1
Max number of retrieved passages: 19
```
Why only 481K out of 808K train queries are presented in top1000.train.tar.gz?
and more importantly, why each presented query **at most** contains only 19 retrieved passages?!

**Comment by bhaskar-mitra** [comment]
> Why only 481K out of 808K train queries are presented in top1000.train.tar.gz?
I believe only ~550K queries had any positively labeled passages. We should have removed the other queries from queries.train.tsv to avoid confusion. Some queries then got dropped in the candidate generation stage (using BM25 without any stopword removal or stemming) because zero passages were retrieved. That brings the number down to ~481K that you are observing.

> why each presented query at most contains only 19 retrieved passages?!
This is definitely weird and shouldn't be the case. I quickly checked my local copy of the top1000.train.txt file and it contains 478,002,393 lines and is 175 GB (uncompressed) / 10.7 GB (compressed). Can you please  verify if these match up with your local copy of the file?

**Comment by amirj** [comment]
Thanks for your reply.
My local copy "top1000.train.gz" (downloaded from [here](https://msmarco.blob.core.windows.net/msmarcoranking/top1000.train.tar.gz)) is 11499957523 bytes and md5sum is 4dc7b43b94c8bd64c630da9a06043cae which is compatible with the website (see ["Dataset files: Size on disk and md5sum" section](https://microsoft.github.io/TREC-2019-Deep-Learning/)). Therefore, my local copy should be exactly as [the remote file](https://msmarco.blob.core.windows.net/msmarcoranking/top1000.train.tar.gz).

**Comment by bhaskar-mitra** [comment]
Hi Amir,

Thanks again for reporting this issue. I investigated this thoroughly last night and found issues with line endings in at least couple of data files (top1000.train.tar.gz and triples.train.small.tsv.tar.gz). The issue has been fixed and the files have been updated. Can you please re-download and verify if you are still noticing any errors?

Some historical context: we inadvertently introduced some line ending related bugs in few of the data files some time ago. It was a human error that should never have happened. We thought we had reverted all the impacted files but clearly we missed some. Sincere apologies for the inconvenience. Please continue to report any other issues you spot with the data.

Best regards,
Bhaskar

**Comment by bhaskar-mitra** [comment]
Hi Amir,

Just making sure you saw the announcement: https://microsoft.github.io/TREC-2019-Deep-Learning/Updated-Deadline-Announcement.

Thanks again for bringing these issues to our notice and sorry for the inconvenience.

Best regards,
Bhaskar

**Comment by amirj** [comment]
Dear Bhaskar,

I do appreciate your effort on this issue.
It seems that the problem has been solved, here is the output of the above investigation code:

```
Number of train queries: 808,731
Total lines in top-1000: 478,002,392
Total queries presented in top-1000: 501233
Min number of retrieved passages: 1
Max number of retrieved passages: 1001
Average number of retrieved passages: 953.65
```

Thank you very much.
