### ISSUE TITLE
We already have the triple format data,  why need Qrels?

### ISSUE THREAD

**Issue by guotong1988** [microsoft/MSMARCO-Passage-Ranking#6]
![image](https://user-images.githubusercontent.com/4702353/62608250-1bf42800-b932-11e9-89e1-83b68e5f94e1.png)

I am new to information retrivial, Thank you very much.
@dfcf93

**Comment by matthew-z** [comment]
IR evaluation tools only accept qrels format, so you don't have to convert the triples into qrels

**Comment by spacemanidol** [comment]
qrels are standard IR evaluation tooling. Tripples are an example of what kind of training data you could use but theoretically you could generate your own.
