### ISSUE TITLE
MSMARCO license ambiguity

### ISSUE THREAD

**Issue by pietruh** [microsoft/MSMARCO-Passage-Ranking#7]
Hi, I am wondering as to what exactly in this repo/project is released on an MIT license and can be used for **commercial** research purposes. On the linked page http://www.msmarco.org/dataset.aspx it is clearly written that the datasets are not intended for this. 

The problem is that in the README, I can see links directly starting a download of the datasets.

Am I missing something here?
It will be great if you could state it clearly in the repository.

**Comment by spacemanidol** [comment]
The repo is under the MIT license. The data has its own requirements.
