### ISSUE TITLE
Encoding issues with triples.train.small

### ISSUE THREAD

**Issue by niazarak** [microsoft/MSMARCO-Passage-Ranking#8]
Hi

I have downloaded `triples.train.small.tar.gz`, extracted the tsv file and here is what I see:
```
faxis a little caffeine ok during pregnancy        We don<C3><A2><C2><80><C2><99>t know a lot about the ef
fects of caffeine during pregnancy on you and your baby. So it<C3><A2><C2><80><C2><99>s best to limit t
he amount you get each day. If you<C3><A2><C2><80><C2><99>re pregnant, limit caffeine to 200 milligrams
 each day. This is about the amount in 1<C3><82><C2><BD> 8-ounce cups of coffee or one 12-ounce cup of
coffee.     It is generally safe for pregnant women to eat chocolate because studies have shown to prov
e certain benefits of eating chocolate during pregnancy. However, pregnant women should ensure their ca
ffeine intake is below 200 mg per day.
```
when I open it as a text file.
You can see how quotation marks and other unicode symbols are encoded incorrectly, and such behaviour can be seen across the dataset.
The problem seems to be that some characters are double encoded, as described for example here https://stackoverflow.com/a/34175283/5230670

**Comment by spacemanidol** [comment]
Given that eveytime I update the dataset it introduces a new type of bias and breaks other old automated systems we will not be fixing this.
