### ISSUE TITLE
ms_marco_eval reference_file structure

### ISSUE THREAD

**Issue by Bernhard-Steindl** [microsoft/MSMARCO-Passage-Ranking#9]
Hi,

I just checked out your IR evaluation script `msmarco_eval.py` and I think I found something inconsistent related to the reference_file format, but I can be wrong too. 

You state in one of the function definitions in the script that the reference_file format is `QUERYID\tPASSAGEID`:
```python
def compute_metrics_from_files(path_to_reference, path_to_candidate, perform_checks=True):
    """Compute MRR metric
    Args:    
    p_path_to_reference_file (str): path to reference file.
        Reference file should contain lines in the following format:
            QUERYID\tPASSAGEID
            Where PASSAGEID is a relevant passage for a query. Note QUERYID can repeat on different lines with different PASSAGEIDs
```

However QRELS are not formatted this way. As defined in the [TREC Relevance Judgements File List](https://trec.nist.gov/data/qrels_eng/) the format of a qrels file is as follows `TOPIC\tITERATION\tDOCUMENT#\tRELEVANCY`, where 

- `TOPIC` is the topic number,
- `ITERATION` is the feedback iteration (almost always zero and not used),
- `DOCUMENT#` is the official document number that corresponds to the "docno" field in the documents, and
- `RELEVANCY` is a binary code of 0 for not relevant and 1 for relevant.

You provided us with QREL files in your Github repo that are already in that latter format.

If you have a look at the function `load_reference_from_stream` that loads the reference file, you see that you also assumed that there are at least 3 tab-separated values. Here is an excerpt
```python
l = l.strip().split('\t')
qid = int(l[0])
qids_to_relevant_passageids[qid].append(int(l[2]))
```

Therefore, I assume that your function documentation for `compute_metrics_from_files` is just unintentionally wrong. I think it should be for example `QUERYID\tITERATION\tPASSAGEID\tRELEVANCY`.

I was a bit confused at first about that and I hope that my note here clarifies the usage of the `ms_marco_eval` script for other newcomers, like me.

**Comment by spacemanidol** [comment]
@Bernhard-St can you make some modifications to the documentation which would help future users and submit it as a pull request?
